import{a as p,S as y,i as n}from"./assets/vendor-hwdYKDic.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const g="48879353-852d93d42efc708c69048a712",h="https://pixabay.com/api/",b=40;async function L(r,t=1){try{return(await p.get(h,{params:{key:g,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:b}})).data}catch(o){throw o}}let d=new y(".gallery .gallery-item a",{captionsData:"alt",captionDelay:250});function v(r,t=!0){const o=document.querySelector(".gallery");if(t&&(d&&d.destroy(),o.innerHTML=""),r.length===0){o.innerHTML="<p>No images found. Try another search.</p>";return}const s=r.map(e=>`
      <div class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </div>`).join("");t?o.innerHTML=s:o.insertAdjacentHTML("beforeend",s),d=new y(".gallery .gallery-item a",{captionsData:"alt",captionDelay:250}),document.querySelector("main").classList.add("visible"),document.querySelector("header").classList.add("searched")}let i=1,f="";const l=document.querySelector(".load-more"),w=document.querySelector(".gallery"),u=document.querySelector(".loader");document.getElementById("search-form").addEventListener("submit",async r=>{r.preventDefault(),i=1,l.style.display="none";const t=document.getElementById("search-input").value.trim();if(!t){n.warning({message:"Please enter a search term!"});return}f=t,await m()});l.addEventListener("click",async()=>{i+=1,await m(!1)});async function m(r=!0){u.style.display="block";try{const t=await L(f,i);if(t.hits.length===0&&r){n.info({message:"Sorry, there are no images matching your search query."});return}if(v(t.hits,r),i*40>=t.totalHits?(l.style.display="none",r||n.info({message:"We're sorry, but you've reached the end of search results."})):l.style.display="block",r&&t.totalHits>0&&n.success({message:`Hooray! We found ${t.totalHits} images.`}),!r){const{height:o}=w.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}catch{n.error({message:"Failed to fetch images. Please try again later."})}finally{u.style.display="none"}}
//# sourceMappingURL=index.js.map
